organization:
  name: Zalando

app:
  title: Api Linter
  baseUrl: http://localhost:3030

backend:
  baseUrl: http://localhost:8081

proxy:
  "/api-linter":
    target: https://infrastructure-api-linter.zalandoapis.com
    headers:
      Authorization: Bearer ${API_LINTER_TOKEN}

release:
  version: 0.0.0
