version: "2017-09-20"  # Don't change this!

pipeline:
  - id: build
    type: script
    vm_config:
      type: linux
      image: "cdp-runtime/nodejs-14"
    commands:
      - desc: Install
        cmd: yarn install
      - desc: running tsc
        cmd: yarn tsc
      - desc: building
        cmd: yarn build
