version: "2017-09-20" # Don't change this!
allow_concurrent_steps: false
pipeline:
  - id: format
    type: script
    vm_config:
      type: linux
      image: "cdp-runtime/nodejs-14"
    commands:
      - desc: Install
        cmd: yarn install
      - desc: lint & tsc.
        cmd: yarn lint
  - id: test
    type: script
    vm_config:
      type: linux
      image: "cdp-runtime/nodejs-14"
    commands:
      - desc: Install dependencies
        cmd: yarn install
      - desc: running tests
        cmd: yarn test test -- --no-watch --silent --forceExit --detectOpenHandles --no-cache --coverage=false --runInBand
  - id: build
    type: script
    vm_config:
      type: linux
      image: "cdp-runtime/nodejs-14"
    commands:
      - desc: Install
        cmd: yarn install
      - desc: building
        cmd: yarn build
